# Generated by Django 6.0.1 on 2026-03-18 03:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_score', models.IntegerField(default=1000)),
                ('games_played', models.IntegerField(default=0)),
                ('total_correct_answers', models.IntegerField(default=0)),
                ('total_wrong_answers', models.IntegerField(default=0)),
                ('total_time_spent', models.IntegerField(default=0)),
                ('average_accuracy', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='player_score', to='students.studentprofile')),
            ],
            options={
                'db_table': 'player_scores',
            },
        ),
    ]
