# Generated by Django 6.0.1 on 2026-01-29 05:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_gamesession_game_level_game_gamesession_game'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamesession',
            name='game',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='games.game'),
        ),
    ]
